// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgHFkyWimSorCi1FVQ_g4FjIY_kp31j6k',
    appId: '1:139089075485:web:e80ac42107b713b7e295f4',
    messagingSenderId: '139089075485',
    projectId: 'trackerexp-be',
    authDomain: 'trackerexp-be.firebaseapp.com',
    storageBucket: 'trackerexp-be.appspot.com',
    measurementId: 'G-J7L00GQPGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj8M-WWzPk7VgXN9_ee6gpqBnqCcNZz0c',
    appId: '1:139089075485:android:61de71dd6714fc44e295f4',
    messagingSenderId: '139089075485',
    projectId: 'trackerexp-be',
    storageBucket: 'trackerexp-be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9MJIajZwwiVSokUhAuR2-K1tt6uqDWNc',
    appId: '1:139089075485:ios:3d3c57d27a368414e295f4',
    messagingSenderId: '139089075485',
    projectId: 'trackerexp-be',
    storageBucket: 'trackerexp-be.appspot.com',
    iosBundleId: 'com.hardik.trackerexp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9MJIajZwwiVSokUhAuR2-K1tt6uqDWNc',
    appId: '1:139089075485:ios:0d48c66056c5f696e295f4',
    messagingSenderId: '139089075485',
    projectId: 'trackerexp-be',
    storageBucket: 'trackerexp-be.appspot.com',
    iosBundleId: 'com.hardik.trackerexp.RunnerTests',
  );
}
